# Generated by Django 3.2.5 on 2021-09-05 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('fname', models.CharField(default=1, max_length=20)),
                ('lname', models.CharField(default=2, max_length=20)),
                ('email', models.EmailField(default='abc@gmail.com', max_length=254)),
            ],
        ),
    ]
