# Generated by Django 3.2.7 on 2021-09-05 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='email',
        ),
        migrations.RemoveField(
            model_name='text',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='text',
            name='lname',
        ),
        migrations.AddField(
            model_name='text',
            name='Uname',
            field=models.CharField(default=100, max_length=30),
            preserve_default=False,
        ),
    ]
